name: Backend CI/CD

on:
  push:
    branches: [ main, backend-java ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: Build with Maven
      run: mvn clean package -DskipTests

    - name: Build Backend Docker Image
      run: docker build -t "${{ secrets.DOCKER_USERNAME }}/cdn-user-backend:latest" .

    - name: Login to Docker Hub
      run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

    - name: Push Docker Image
      run: docker push "${{ secrets.DOCKER_USERNAME }}/cdn-user-backend:latest"